// types Groupes 
export const ALL_GROUPE_ACTIVE = 'ALL_GROUPE_ACTIVE'
export const ALL_GROUPE = 'ALL_GROUPE'
export const ALL_GROUPE_WITH_NIVEAU = 'ALL_GROUPE_WITH_NIVEAU'

export const GET_ERROR_GROUPE = 'GET_ERROR_GROUPE'


// types Professeur 
export const ALL_PROF = 'ALL_PROF'
export const GET_ERROR_PROF = 'GET_ERROR_PROF'


// types Fillier 
export const ALL_FILLIER = 'ALL_FILLIER'

export const GET_ERROR_FILLIER = 'GET_ERROR_FILLIER'


// types Niveau 
export const ALL_NIVEAU = 'ALL_NIVEAU'

export const GET_ERROR_NIVEAU = 'GET_ERROR_NIVEAU'


// types Date 
export const ALL_DATES = 'ALL_DATES'
export const ALL_DATES_WITH_DAYS = 'ALL_DATES_WITH_DAYS'
export const DATES_DESPO_OF_PROF = 'DATES_DESPO_OF_PROF'
export const ALL_DATES_SECONDAIRE = 'ALL_DATES_SECONDAIRE'
export const ONE_DATES_SECONDAIRE = 'ONE_DATES_SECONDAIRE'

export const GET_ERROR_DATES = 'GET_ERROR_DATES'



// types seance 
export const ALL_SEANCE_OF_PROF = 'ALL_SEANCE_OF_PROF'
export const MSG_ADD_SEANCE = 'MSG_ADD_SEANCE'
export const MSG_DELETE_SEANCE = 'MSG_DELETE_SEANCE'
export const TIME_AVAILABLE_PROF_GP = 'TIME_AVAILABLE_PROF_GP'
export const MESSAGE_VALIDATION_DATE = 'MESSAGE_VALIDATION_DATE'
export const GET_ERROR_EMPLOI_OF_PROF = 'MESSAGE_VALIDATION_DATE'
export const MSG_DELETE_EMPLOI = 'MESSAGE_VALIDATION_DATE'
export const EMPLOI_GROUPES = 'EMPLOI_GROUPES'
export const MSG_ADD_SEANCE_TEMPORAIRE = 'MSG_ADD_SEANCE_TEMPORAIRE'


export const GET_ERROR_SEANCE_OF_PROF = 'GET_ERROR_SEANCE_OF_PROF'


// types Salle 
export const SALLES_DISPO_WITH_JOUR_DATEHEUR = 'SALLES_DISPO_WITH_JOUR_DATEHEUR'

export const GET_ERROR_SALLE = 'GET_ERROR_SALLE'


// types Encadrement 
export const MSG_ADD_ENCADRE = 'MSG_ADD_ENCADRE'
export const ALL_GROUPE_ENCADRE_PROF = 'ALL_GROUPE_ENCADRE_PROF'
export const DELETE_GROUPE_ENCADRE_PROF = 'DELETE_GROUPE_ENCADRE_PROF'
export const INITIAL_MESSAGE = 'INITIAL_MESSAGE'
export const SALLE_TIME_AVAILABLE_PROF_GRP = 'SALLE_TIME_AVAILABLE_PROF_GRP'
export const GET_ERROR_ENCADRE = 'GET_ERROR_ENCADRE'


// types Module 
export const ALL_MODULES = 'ALL_MODULES'
export const ALL_MODULES_OF_FILLIER = 'ALL_MODULES_OF_FILLIER'
export const ALL_MODULES_OF_PROF = 'ALL_MODULES_OF_PROF'
export const GET_ERROR_MODULES = 'GET_ERROR_MODULES'




// Login User
export const LOGIN_USER = 'LOGIN_USER'
export const USER_TYPE = 'USER_TYPE'
export const LOGIN_ERROR = 'LOGIN_ERROR'
